#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 15.20Release
// Tag = development-akw-15.20.00-0
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the profile CoursePoint type as an enum
   /// </summary>  
   public enum CoursePoint : byte
   {
      Generic = 0, 
      Summit = 1, 
      Valley = 2, 
      Water = 3, 
      Food = 4, 
      Danger = 5, 
      Left = 6, 
      Right = 7, 
      Straight = 8, 
      FirstAid = 9, 
      FourthCategory = 10, 
      ThirdCategory = 11, 
      SecondCategory = 12, 
      FirstCategory = 13, 
      HorsCategory = 14, 
      Sprint = 15, 
      LeftFork = 16, 
      RightFork = 17, 
      MiddleFork = 18, 
      SlightLeft = 19, 
      SharpLeft = 20, 
      SlightRight = 21, 
      SharpRight = 22, 
      UTurn = 23, 
      Invalid = 0xFF   
      
   }
}

