#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 15.20Release
// Tag = development-akw-15.20.00-0
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the profile MesgNum type as a class
   /// </summary>  
   public static class MesgNum 
   {
      public const ushort FileId = 0;
      public const ushort Capabilities = 1;
      public const ushort DeviceSettings = 2;
      public const ushort UserProfile = 3;
      public const ushort HrmProfile = 4;
      public const ushort SdmProfile = 5;
      public const ushort BikeProfile = 6;
      public const ushort ZonesTarget = 7;
      public const ushort HrZone = 8;
      public const ushort PowerZone = 9;
      public const ushort MetZone = 10;
      public const ushort Sport = 12;
      public const ushort Goal = 15;
      public const ushort Session = 18;
      public const ushort Lap = 19;
      public const ushort Record = 20;
      public const ushort Event = 21;
      public const ushort DeviceInfo = 23;
      public const ushort Workout = 26;
      public const ushort WorkoutStep = 27;
      public const ushort Schedule = 28;
      public const ushort WeightScale = 30;
      public const ushort Course = 31;
      public const ushort CoursePoint = 32;
      public const ushort Totals = 33;
      public const ushort Activity = 34;
      public const ushort Software = 35;
      public const ushort FileCapabilities = 37;
      public const ushort MesgCapabilities = 38;
      public const ushort FieldCapabilities = 39;
      public const ushort FileCreator = 49;
      public const ushort BloodPressure = 51;
      public const ushort SpeedZone = 53;
      public const ushort Monitoring = 55;
      public const ushort TrainingFile = 72;
      public const ushort Hrv = 78;
      public const ushort Length = 101;
      public const ushort MonitoringInfo = 103;
      public const ushort Pad = 105;
      public const ushort SlaveDevice = 106;
      public const ushort CadenceZone = 131;
      public const ushort SegmentLap = 142;
      public const ushort MemoGlob = 145;
      public const ushort SegmentId = 148;
      public const ushort SegmentLeaderboardEntry = 149;
      public const ushort SegmentPoint = 150;
      public const ushort SegmentFile = 151;
      public const ushort MfgRangeMin = 0xFF00; // 0xFF00 - 0xFFFE reserved for manufacturer specific messages
      public const ushort MfgRangeMax = 0xFFFE; // 0xFF00 - 0xFFFE reserved for manufacturer specific messages
      public const ushort Invalid = (ushort)0xFFFF;   
      
   }
}

