#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.00Release
// Tag = development-akw-16.00.00-0
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the profile Sport type as an enum
   /// </summary>  
   public enum Sport : byte
   {
      Generic = 0, 
      Running = 1, 
      Cycling = 2, 
      Transition = 3, 
      FitnessEquipment = 4, 
      Swimming = 5, 
      Basketball = 6, 
      Soccer = 7, 
      Tennis = 8, 
      AmericanFootball = 9, 
      Training = 10, 
      Walking = 11, 
      CrossCountrySkiing = 12, 
      AlpineSkiing = 13, 
      Snowboarding = 14, 
      Rowing = 15, 
      Mountaineering = 16, 
      Hiking = 17, 
      Multisport = 18, 
      Paddling = 19, 
      Flying = 20, 
      EBiking = 21, 
      All = 254, 
      Invalid = 0xFF   
      
   }
}

