#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 15.20Release
// Tag = development-akw-15.20.00-0
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the profile SportBits2 type as a class
   /// </summary>  
   public static class SportBits2 
   {
      public const byte Mountaineering = 0x01;
      public const byte Hiking = 0x02;
      public const byte Multisport = 0x04;
      public const byte Paddling = 0x08;
      public const byte Flying = 0x10;
      public const byte EBiking = 0x20;
      public const byte Invalid = (byte)0x00;   
      
   }
}

