#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.00Release
// Tag = development-akw-16.00.00-0
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the profile SubSport type as an enum
   /// </summary>  
   public enum SubSport : byte
   {
      Generic = 0, 
      Treadmill = 1, 
      Street = 2, 
      Trail = 3, 
      Track = 4, 
      Spin = 5, 
      IndoorCycling = 6, 
      Road = 7, 
      Mountain = 8, 
      Downhill = 9, 
      Recumbent = 10, 
      Cyclocross = 11, 
      HandCycling = 12, 
      TrackCycling = 13, 
      IndoorRowing = 14, 
      Elliptical = 15, 
      StairClimbing = 16, 
      LapSwimming = 17, 
      OpenWater = 18, 
      FlexibilityTraining = 19, 
      StrengthTraining = 20, 
      WarmUp = 21, 
      Match = 22, 
      Exercise = 23, 
      Challenge = 24, 
      IndoorSkiing = 25, 
      CardioTraining = 26, 
      IndoorWalking = 27, 
      EBikeFitness = 28, 
      All = 254, 
      Invalid = 0xFF   
      
   }
}

