#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.00Release
// Tag = development-akw-16.00.00-0
////////////////////////////////////////////////////////////////////////////////

#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;


namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the HrmProfile profile message.
   /// </summary>  
   public class HrmProfileMesg : Mesg 
   {    
      #region Fields     
      #endregion

      #region Constructors                 
      public HrmProfileMesg() : base(Profile.mesgs[Profile.HrmProfileIndex])               
      {                 
      }
      
      public HrmProfileMesg(Mesg mesg) : base(mesg)
      {
      }
      #endregion // Constructors

      #region Methods    
      ///<summary>      
      /// Retrieves the MessageIndex field</summary>
      /// <returns>Returns nullable ushort representing the MessageIndex field</returns>      
      public ushort? GetMessageIndex()   
      {                
         return (ushort?)GetFieldValue(254, 0, Fit.SubfieldIndexMainField);                     
      }

      /// <summary>        
      /// Set MessageIndex field</summary>
      /// <param name="messageIndex_">Nullable field value to be set</param>      
      public void SetMessageIndex(ushort? messageIndex_) 
      {  
         SetFieldValue(254, 0, messageIndex_, Fit.SubfieldIndexMainField);
      }
          
      ///<summary>      
      /// Retrieves the Enabled field</summary>
      /// <returns>Returns nullable Bool enum representing the Enabled field</returns>      
      public Bool? GetEnabled()   
      { 
         object obj = GetFieldValue(0, 0, Fit.SubfieldIndexMainField);
         Bool? value = obj == null ? (Bool?)null : (Bool)obj;
         return value;                     
      }

      /// <summary>        
      /// Set Enabled field</summary>
      /// <param name="enabled_">Nullable field value to be set</param>      
      public void SetEnabled(Bool? enabled_) 
      {  
         SetFieldValue(0, 0, enabled_, Fit.SubfieldIndexMainField);
      }
          
      ///<summary>      
      /// Retrieves the HrmAntId field</summary>
      /// <returns>Returns nullable ushort representing the HrmAntId field</returns>      
      public ushort? GetHrmAntId()   
      {                
         return (ushort?)GetFieldValue(1, 0, Fit.SubfieldIndexMainField);                     
      }

      /// <summary>        
      /// Set HrmAntId field</summary>
      /// <param name="hrmAntId_">Nullable field value to be set</param>      
      public void SetHrmAntId(ushort? hrmAntId_) 
      {  
         SetFieldValue(1, 0, hrmAntId_, Fit.SubfieldIndexMainField);
      }
          
      ///<summary>      
      /// Retrieves the LogHrv field</summary>
      /// <returns>Returns nullable Bool enum representing the LogHrv field</returns>      
      public Bool? GetLogHrv()   
      { 
         object obj = GetFieldValue(2, 0, Fit.SubfieldIndexMainField);
         Bool? value = obj == null ? (Bool?)null : (Bool)obj;
         return value;                     
      }

      /// <summary>        
      /// Set LogHrv field</summary>
      /// <param name="logHrv_">Nullable field value to be set</param>      
      public void SetLogHrv(Bool? logHrv_) 
      {  
         SetFieldValue(2, 0, logHrv_, Fit.SubfieldIndexMainField);
      }
          
      ///<summary>      
      /// Retrieves the HrmAntIdTransType field</summary>
      /// <returns>Returns nullable byte representing the HrmAntIdTransType field</returns>      
      public byte? GetHrmAntIdTransType()   
      {                
         return (byte?)GetFieldValue(3, 0, Fit.SubfieldIndexMainField);                     
      }

      /// <summary>        
      /// Set HrmAntIdTransType field</summary>
      /// <param name="hrmAntIdTransType_">Nullable field value to be set</param>      
      public void SetHrmAntIdTransType(byte? hrmAntIdTransType_) 
      {  
         SetFieldValue(3, 0, hrmAntIdTransType_, Fit.SubfieldIndexMainField);
      }
                        
      #endregion // Methods
   } // Class
} // namespace
