#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2015 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.00Release
// Tag = development-akw-16.00.00-0
////////////////////////////////////////////////////////////////////////////////

#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;


namespace Dynastream.Fit
{
   /// <summary>
   /// Implements the MetZone profile message.
   /// </summary>  
   public class MetZoneMesg : Mesg 
   {    
      #region Fields     
      #endregion

      #region Constructors                 
      public MetZoneMesg() : base(Profile.mesgs[Profile.MetZoneIndex])               
      {                 
      }
      
      public MetZoneMesg(Mesg mesg) : base(mesg)
      {
      }
      #endregion // Constructors

      #region Methods    
      ///<summary>      
      /// Retrieves the MessageIndex field</summary>
      /// <returns>Returns nullable ushort representing the MessageIndex field</returns>      
      public ushort? GetMessageIndex()   
      {                
         return (ushort?)GetFieldValue(254, 0, Fit.SubfieldIndexMainField);                     
      }

      /// <summary>        
      /// Set MessageIndex field</summary>
      /// <param name="messageIndex_">Nullable field value to be set</param>      
      public void SetMessageIndex(ushort? messageIndex_) 
      {  
         SetFieldValue(254, 0, messageIndex_, Fit.SubfieldIndexMainField);
      }
          
      ///<summary>      
      /// Retrieves the HighBpm field</summary>
      /// <returns>Returns nullable byte representing the HighBpm field</returns>      
      public byte? GetHighBpm()   
      {                
         return (byte?)GetFieldValue(1, 0, Fit.SubfieldIndexMainField);                     
      }

      /// <summary>        
      /// Set HighBpm field</summary>
      /// <param name="highBpm_">Nullable field value to be set</param>      
      public void SetHighBpm(byte? highBpm_) 
      {  
         SetFieldValue(1, 0, highBpm_, Fit.SubfieldIndexMainField);
      }
          
      ///<summary>      
      /// Retrieves the Calories field
      /// Units: kcal / min</summary>
      /// <returns>Returns nullable float representing the Calories field</returns>      
      public float? GetCalories()   
      {                
         return (float?)GetFieldValue(2, 0, Fit.SubfieldIndexMainField);                     
      }

      /// <summary>        
      /// Set Calories field
      /// Units: kcal / min</summary>
      /// <param name="calories_">Nullable field value to be set</param>      
      public void SetCalories(float? calories_) 
      {  
         SetFieldValue(2, 0, calories_, Fit.SubfieldIndexMainField);
      }
          
      ///<summary>      
      /// Retrieves the FatCalories field
      /// Units: kcal / min</summary>
      /// <returns>Returns nullable float representing the FatCalories field</returns>      
      public float? GetFatCalories()   
      {                
         return (float?)GetFieldValue(3, 0, Fit.SubfieldIndexMainField);                     
      }

      /// <summary>        
      /// Set FatCalories field
      /// Units: kcal / min</summary>
      /// <param name="fatCalories_">Nullable field value to be set</param>      
      public void SetFatCalories(float? fatCalories_) 
      {  
         SetFieldValue(3, 0, fatCalories_, Fit.SubfieldIndexMainField);
      }
                        
      #endregion // Methods
   } // Class
} // namespace
